### ISSUE TITLE
代码不全吧

### ISSUE THREAD

**Issue by alibabazhang** [GitHub-Laziji/mybatis-generator#1]
楼主 你好，想看看全部代码，应该缺少 common 和parent模块吧？？

**Comment by GitHub-Laziji** [comment]
pom.xml中为了简便引人了 [commons-mybatis](https://github.com/GitHub-Laziji/commons-mybatis) 和 父依赖 [commons-parent](https://github.com/GitHub-Laziji/commons-parent)  
下载下来 maven打包就行了  

里面用到主要是一些springboot的依赖 和apache的工具类

**Comment by alibabazhang** [comment]
好的，我在看看多谢

**Comment by GitHub-Laziji** [comment]
我修改提交了, 把那两个项目中的依赖直接移过来了  更新一下就行
